// src/components/PrintAdmissionSlip.jsx
import React, { useState } from 'react';
import { issueAdmissionSlip } from '../services/api';
import { Printer, User, Book, Users } from 'lucide-react';

const PrintAdmissionSlip = () => {
  const [formData, setFormData] = useState({
    studentName: '',
    year: '',
    section: ''
  });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    setResult(null);

    try {
      const response = await issueAdmissionSlip(formData);
      setResult(response.data);
      
      // Reset form
      setFormData({
        studentName: '',
        year: '',
        section: ''
      });
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to issue admission slip');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    if (result?.slip) {
      const printWindow = window.open('', '_blank');
      printWindow.document.write(`
        <html>
          <head>
            <title>Admission Slip - ${result.slip.slip_number}</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; }
              .header { text-align: center; margin-bottom: 30px; }
              .slip-info { margin: 20px 0; }
              .field { margin: 10px 0; }
              .label { font-weight: bold; }
              .footer { margin-top: 50px; text-align: center; font-size: 12px; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>UNIVERSITY ADMISSION SLIP</h1>
              <h2>Policy Violation Notification</h2>
            </div>
            <div class="slip-info">
              <div class="field">
                <span class="label">Slip Number:</span> ${result.slip.slip_number}
              </div>
              <div class="field">
                <span class="label">Student Name:</span> ${formData.studentName}
              </div>
              <div class="field">
                <span class="label">Year & Section:</span> ${formData.year} - ${formData.section}
              </div>
              <div class="field">
                <span class="label">Date Issued:</span> ${new Date().toLocaleDateString()}
              </div>
            </div>
            <div class="instructions">
              <p><strong>Instructions:</strong></p>
              <p>1. This admission slip must be filled out completely by the student</p>
              <p>2. Return the completed form to the guidance counselor</p>
              <p>3. Failure to comply may result in further disciplinary action</p>
            </div>
            <div class="footer">
              <p>Generated by CounselMate System</p>
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="max-w-2xl mx-auto">
      <div className="bg-white rounded-lg shadow-lg p-6">
        <div className="flex items-center mb-6">
          <Printer className="w-8 h-8 text-blue-600 mr-3" />
          <h1 className="text-2xl font-bold text-gray-900">Print Admission Slip</h1>
        </div>

        <p className="text-gray-600 mb-6">
          Issue an admission slip for a student who has violated university policy.
          The system will log the issuance and generate a printable slip.
        </p>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Student Name
            </label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <input
                type="text"
                name="studentName"
                value={formData.studentName}
                onChange={handleChange}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                placeholder="Enter student's full name"
                required
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Year Level
            </label>
            <div className="relative">
              <Book className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <select
                name="year"
                value={formData.year}
                onChange={handleChange}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                required
              >
                <option value="">Select year level</option>
                <option value="1st Year">1st Year</option>
                <option value="2nd Year">2nd Year</option>
                <option value="3rd Year">3rd Year</option>
                <option value="4th Year">4th Year</option>
              </select>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Section
            </label>
            <div className="relative">
              <Users className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <input
                type="text"
                name="section"
                value={formData.section}
                onChange={handleChange}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                placeholder="Enter section (e.g., A, B, C)"
                required
              />
            </div>
          </div>

          {error && (
            <div className="p-3 text-sm text-red-700 bg-red-100 rounded-lg">
              {error}
            </div>
          )}

          {result && (
            <div className="p-4 text-sm text-green-700 bg-green-100 rounded-lg">
              <p className="font-medium">Admission slip issued successfully!</p>
              <p>Slip Number: {result.slip.slip_number}</p>
              <button
                type="button"
                onClick={handlePrint}
                className="mt-2 bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 transition-colors"
              >
                Print Slip
              </button>
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-600 text-white py-3 px-4 rounded-lg hover:bg-blue-700 focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-medium"
          >
            {loading ? 'Issuing Slip...' : 'Issue Admission Slip'}
          </button>
        </form>
      </div>
    </div>
  );
};

export default PrintAdmissionSlip;